SELECT NAME, BIRTHDAY, TYPE
FROM (SELECT NAME,
             BIRTHDAY,
             CASE
                 WHEN BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM WORKER) THEN 'ELDEST'
                 WHEN BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM WORKER) THEN 'YOUNGEST'
                 END AS TYPE
      FROM WORKER) AS WORKER_INFO
WHERE TYPE = 'ELDEST'
   OR TYPE = 'YOUNGEST';